steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/red-planet-226907/studentapi', '.']
  timeout: 500s
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/red-planet-226907/studentapi']
- name: 'alpine'
  args: ['ls', '-la']
  dir: '/app'  
#- name: 'gcr.io/cloud-builders/gcloud'
 # args: ['app', 'deploy', '/StudentAPI/app.yaml']
  #timeout: 600s
options:
    machineType: 'N1_HIGHCPU_8'
timeout: 660s
images: ['gcr.io/red-planet-226907/studentapi']
