steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/red-planet-226907/studentapi', '.']
  timeout: 500s
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/red-planet-226907/studentapi']
- name: 'gcr.io/cloud-builders/kubectl'
  args:
  - 'set'
  - 'image'
  - 'deployment/studentapi'
  - 'my-container=gcr.io/red-planet-226907/studentapi'
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=us-east1-c'
  - 'CLOUDSDK_CONTAINER_CLUSTER=standard-cluster-1'
options:
    machineType: 'N1_HIGHCPU_8'
timeout: 660s
images: ['gcr.io/red-planet-226907/studentapi']
