steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/red-planet-226907/studentapi', '.']
  timeout: 500s
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/red-planet-226907/studentapi'] 
- name: 'gcr.io/cloud-builders/docker'
  args: ['run', '--rm', '-p', '8080:8080', 'gcr.io/red-planet-226907/studentapi']
options:
    machineType: 'N1_HIGHCPU_8'
timeout: 660s
images: ['gcr.io/red-planet-226907/studentapi']
